<?php
/**
 * Created by PhpStorm.
 * User: joshi
 * Date: 23.10.13
 * Time: 16:16
 */

namespace Phpforce\SoapClient;

use Phpforce\SoapClient\Soap\SoapConnection;

class EnterpriseClient extends Client
{
    /**
     * @var callable|null
     */
    private $sfToPhpConverter;

    /**
     * @override
     *
     * {@inheritdoc}
     */
    public function query($query)
    {
        $res = parent::query($query); // TODO: Change the autogenerated stub

        $res->setSfToPhpConverter($this->getSfToPhpConverter());

        return $res;
    }

    /**
     * @override
     *
     * {@inheritdoc}
     */
    public function queryAll($query)
    {
        $res = parent::queryAll($query); // TODO: Change the autogenerated stub

        $res->setSfToPhpConverter($this->getSfToPhpConverter());

        return $res;
    }

    /**
     * @return callable
     */
    private function getSfToPhpConverter()
    {
        if(null === $this->sfToPhpConverter)
        {
            $this->sfToPhpConverter = function($object)
            {
                if($object instanceof Result\QueryResult)
                {
                    new Result\RecordIterator($this, $object, $this->getSfToPhpConverter());
                }
                elseif(is_object($object))
                {
                    foreach($object AS &$value)
                    {
                        $value = $this->getSfToPhpConverter($value);
                    }
                }
                return $object;
            };
        }
        return $this->sfToPhpConverter;
    }
} 