<?php
namespace Phpforce\SoapClient;

class EnterpriseClient extends Client
{
    /**
     * @var callable|null
     */
    private $sfToPhpConverter;

    /**
     * {@inheritdoc}
     */
    public function query($query)
    {
        $res = parent::query($query); // TODO: Change the autogenerated stub

        $res->setSfToPhpConverter($this->getSfToPhpConverter());

        return $res;
    }

    /**
     * {@inheritdoc}
     */
    public function queryAll($query)
    {
        $res = parent::queryAll($query); // TODO: Change the autogenerated stub

        $res->setSfToPhpConverter($this->getSfToPhpConverter());

        return $res;
    }

    /**
     * @return callable
     */
    public function getSfToPhpConverter()
    {
        if(null === $this->sfToPhpConverter)
        {
            $self = $this;

            $this->sfToPhpConverter = function($object) use ($self)
            {
                if($object instanceof Result\QueryResult)
                {
                    new Result\RecordIterator($self, $object, $self->getSfToPhpConverter());
                }
                elseif(is_object($object))
                {
                    foreach($object AS &$value)
                    {
                        $value = $self->getSfToPhpConverter($value);
                    }
                }
                return $object;
            };
        }
        return $this->sfToPhpConverter;
    }
} 